services:

  application_service:
    build:
      dockerfile: ./Dockerfile
    restart: always
    container_name: "application_service"
    env_file:
      - .env
    ports:
      - '5033:5033'
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongodb: